2025-05-21 00:06:25,290 INFO    Thread-2 (_run_job):8219 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_setup.py:_flush():67] Configure stats pid to 8219
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_setup.py:_flush():67] Loading settings from /Users/karanagrawal/.config/wandb/settings
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_setup.py:_flush():67] Loading settings from /Users/karanagrawal/Desktop/Sem 2/DL/DA6401_Assignment3/wandb/settings
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/karanagrawal/Desktop/Sem 2/DL/DA6401_Assignment3/wandb/run-20250521_000625-p1vsb0oq/logs/debug.log
2025-05-21 00:06:25,291 INFO    Thread-2 (_run_job):8219 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/karanagrawal/Desktop/Sem 2/DL/DA6401_Assignment3/wandb/run-20250521_000625-p1vsb0oq/logs/debug-internal.log
2025-05-21 00:06:25,292 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():761] calling init triggers
2025-05-21 00:06:25,292 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'bidirectional': True, 'cell_type': 'LSTM', 'dropout': 0.5, 'emb_dim': 64, 'hidden_size': 512, 'learning_rate': 0.001, 'num_dec_layers': 3, 'num_enc_layers': 3}
config: {'_wandb': {}}
2025-05-21 00:06:25,292 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():784] starting backend
2025-05-21 00:06:25,292 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():788] sending inform_init request
2025-05-21 00:06:25,333 INFO    Thread-2 (_run_job):8219 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-21 00:06:25,334 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():803] backend started and connected
2025-05-21 00:06:25,339 INFO    Thread-2 (_run_job):8219 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 16, 'bidirectional': True, 'cell_type': 'LSTM', 'dropout': 0.5, 'emb_dim': 64, 'hidden_size': 512, 'learning_rate': 0.001, 'num_dec_layers': 3, 'num_enc_layers': 3}
2025-05-21 00:06:25,342 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():896] updated telemetry
2025-05-21 00:06:25,365 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-21 00:06:26,023 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():995] starting run threads in backend
2025-05-21 00:06:26,531 INFO    Thread-2 (_run_job):8219 [wandb_run.py:_console_start():2377] atexit reg
2025-05-21 00:06:26,532 INFO    Thread-2 (_run_job):8219 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-21 00:06:26,532 INFO    Thread-2 (_run_job):8219 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-21 00:06:26,532 INFO    Thread-2 (_run_job):8219 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-21 00:06:26,535 INFO    Thread-2 (_run_job):8219 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-21 00:10:15,673 WARNING MsgRouterThr:8219 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-21 00:10:15,676 INFO    MsgRouterThr:8219 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
